javaee/ch03/javaquiz-rest/src/java/com/corejsf/QuizBean.java
package com.corejsf;

import java.io.Serializable;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import javax.inject.Named; 
   // or import javax.faces.bean.ManagedBean;
import javax.enterprise.context.SessionScoped; 
   // or import javax.faces.bean.SessionScoped;

@Named // or @ManagedBean
@SessionScoped
public class QuizBean implements Serializable {
   private int currentProblem;
   private int tries;
   private String response = "";
   private String correctAnswer;

   // Here, we hardwire the problems. In a real application,
   // they would come from a database
   private ArrayList<Problem> problems = new ArrayList<Problem>(Arrays.asList(
      new Problem(
         "What trademarked slogan describes Java development? Write once, ...",
         "run anywhere"),
      new Problem(
         "What are the first 4 bytes of every class file (in hexadecimal)?",
         "CAFEBABE"),
      new Problem(
         "What does this statement print? System.out.println(1+\"2\");",
         "12"),
      new Problem(
         "Which Java keyword is used to define a subclass?",
         "extends"),
      new Problem(
         "What was the original name of the Java programming language?",
         "Oak"),
      new Problem(
         "Which java.util class describes a point in time?",
         "Date")));

   private int[] scores = new int[problems.size()];

   public String getQuestion() { 
      return problems.get(currentProblem).getQuestion();
   }

   public String getAnswer() { return correctAnswer; }

   public int getScore() {
      int score = 0;
      for (int s : scores) score += s; 
      return score;
   }

   public String getResponse() { return response; }
   public void setResponse(String newValue) { response = newValue; }

   public int getCurrentProblem() { return currentProblem; }
   public void setCurrentProblem(int newValue) { currentProblem = newValue; }

   public String getSkipOutcome() {
      if (currentProblem < problems.size() - 1) return "index";
      else return "done";
   }

   public String answerAction() {
      tries++;
      if (problems.get(currentProblem).isCorrect(response)) {
         scores[currentProblem] = 1;
         nextProblem();
         if (currentProblem == problems.size()) return "done";
         else return "success";
      }
      else {
         scores[currentProblem] = 0;            
         if (tries == 1) return "again";
         else {
            nextProblem();
            if (currentProblem == problems.size()) return "done";
            else return "failure";
         }
      }
   }

   public String startOverAction() {
      Collections.shuffle(problems);
      currentProblem = 0;
      for (int i = 0; i < scores.length; i++)
         scores[i] = 0;
      tries = 0;
      response = "";
      return "startOver";
   }

   private void nextProblem() {
      correctAnswer = problems.get(currentProblem).getAnswer();
      currentProblem++;
      tries = 0;
      response = "";
   }
}

javaee/ch03/javaquiz-rest/web/again.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html">
   <h:head>
      <title>#{msgs.title}</title>
   </h:head>
   <h:body>
      <h:form>
         <p>#{msgs.notCorrect}</p>
         <p>#{quizBean.question}</p>
         <p><h:inputText value="#{quizBean.response}"/></p>
         <p>
            <h:commandButton value="#{msgs.checkAnswer}"
                             action="#{quizBean.answerAction}"/>
         </p>
         <p><h:link outcome="#{quizBean.skipOutcome}" value="Skip">
            <f:param name="q" value="#{quizBean.currentProblem + 1}"/>
         </h:link>
         </p>
      </h:form>
   </h:body>
</html>

javaee/ch03/javaquiz-rest/web/done.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html">
   <h:head>
      <title>#{msgs.title}</title>
   </h:head>
   <h:body>
      <h:form>
         <p>#{msgs.thankYou}
         <h:outputFormat value="#{msgs.score}">
            <f:param value="#{quizBean.score}"/>
         </h:outputFormat>
         </p>
         <p>
            <h:commandButton value="#{msgs.startOver}"
                             action="#{quizBean.startOverAction}"/>
         </p>
      </h:form>
   </h:body>
</html>

javaee/ch03/javaquiz-rest/web/failure.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html">
   <h:head>
      <title>#{msgs.title}</title>
   </h:head>
   <h:body>
      <h:form>
         <p>
            #{msgs.stillNotCorrect}
            <h:outputFormat value="#{msgs.correctAnswer}">
               <f:param value="#{quizBean.answer}"/>
            </h:outputFormat>
         </p>
         <p>#{msgs.nextProblem}</p>
         <p>#{quizBean.question}</p>
         <p>
            <h:inputText value="#{quizBean.response}"/>
         </p>
         <p>
            <h:commandButton value="#{msgs.checkAnswer}"
                             action="#{quizBean.answerAction}"/>
         </p>
         <p>
            <h:link outcome="#{quizBean.skipOutcome}" value="Skip">
               <f:param name="q" value="#{quizBean.currentProblem + 1}"/>
            </h:link>
         </p>
      </h:form>
   </h:body>
</html>

javaee/ch03/javaquiz-rest/web/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core" 
      xmlns:h="http://java.sun.com/jsf/html">
   <f:metadata>
      <f:viewParam name="q" value="#{quizBean.currentProblem}"/>
   </f:metadata>
   <h:head>
      <title>#{msgs.title}</title>
   </h:head>
   <h:body>
      <h:form>
         <p>#{quizBean.question}</p>
         <p><h:inputText value="#{quizBean.response}"/></p>
         <p><h:commandButton value="#{msgs.checkAnswer}"
         action="#{quizBean.answerAction}"/></p>
         <p><h:link outcome="#{quizBean.skipOutcome}" value="Skip">
            <f:param name="q" value="#{quizBean.currentProblem + 1}"/>
         </h:link>
         </p>
      </h:form>
   </h:body>
</html>

javaee/ch03/javaquiz-rest/web/success.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html">
   <h:head>
      <title>#{msgs.title}</title>
   </h:head>
   <h:body>
      <h:form>
         <p>
            #{msgs.correct}
            <h:outputFormat value="#{msgs.score}">
               <f:param value="#{quizBean.score}"/>
            </h:outputFormat>
         </p>
         <p>#{msgs.nextProblem}</p>
         <p>#{quizBean.question}</p>
         <p><h:inputText value="#{quizBean.response}"/></p>
         <p>
            <h:commandButton value="#{msgs.checkAnswer}"
                             action="#{quizBean.answerAction}"/>
         </p>
         <p><h:link outcome="#{quizBean.skipOutcome}" value="Skip">
            <f:param name="q" value="#{quizBean.currentProblem + 1}"/>
         </h:link>
         </p>         
      </h:form>
   </h:body>
</html>